AllCops:
  Exclude:
    - config/*
    - config/*/*.rb
    - bin/*
    - db/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Metrics/LineLength:
  Max: 95

MethodLength:
  Max: 35

Style/FrozenStringLiteralComment:
  Enabled: false
